### ISSUE TITLE
Get Started Example Throwing Exception

### ISSUE THREAD

**Issue by alexdriedger** [Drnoodle/fastpose#2]
When following the instructions for the Get Started page, I get the following error

```
2019-12-21 22:47:55.524927: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "demo_2d.py", line 69, in <module>
    start(default_media, int(argv[2]))
  File "demo_2d.py", line 36, in start
    fps = int(1/(time.time()-tmpTime))
ZeroDivisionError: float division by zero
```

My teammate also ran had the same error when doing the Get Started example on their computer

OS: Windows 10

**Comment by Fungus-Light** [comment]
this is caused by the fps counter, you can modify the code demo_2d.py line 36 
fps = int(1/(time.time()-tmpTime))  ==>  fps = int(1/(time.time()-tmpTime+1))

this is not perfect,but it truly make the code work,only with the fps counter work improperly。
